# Generated by Django 4.2.5 on 2023-10-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                ("district_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "district_name",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
            ],
            options={
                "db_table": "District",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "jurisdiction_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "jurisdiction_name",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
            ],
            options={
                "db_table": "Jurisdiction",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "neighborhood_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "neighborhood_name",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
            ],
            options={
                "db_table": "Neighborhood",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                ("province_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "province_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "Province",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=400)),
                (
                    "natural_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("lastname", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("phone", models.IntegerField(blank=True, null=True)),
                (
                    "recovery_email",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "sec_question",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "User_profile",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                ("village_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "village_name",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
            ],
            options={
                "db_table": "Village",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ZipCode",
            fields=[
                ("zip_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "country_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "Zip_code",
                "managed": False,
            },
        ),
    ]
